import './globals.css'
import { Edu_TAS_Beginner } from 'next/font/google'
import styles from './page.module.css'
import { Navbar, SideMenu, Footer } from './components/index'
import { StateContext } from './context/StateContext'

const inter = Edu_TAS_Beginner({ subsets: ['latin'] })

export const metadata = {
  title: 'Two4Line outfit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>
        {/* {isOpen && <SideMenu />} */}
          {/* <SideMenu/> */}
          {/* <header className={styles.header}>
            <Navbar/>
          </header> */}
          {/* <main className={styles.main}> */}
          <main>
          {children}
          </main>
          {/* <footer> */}
            {/* <Footer/> */}
          {/* </footer> */}
        </StateContext>
      </body>
    </html>
  )
}
